### PR TITLE
Add a plain ruby example for additional form fields

### PR DESCRIPTION
**Pull request by janpio**
I needed a few minutes to understand how the rails 4 example could be transformed to plain ruby. I am probably not the only one, so I created a PR with the code that is working for me.

Also some unrelated tiny improvements to the other text.

### CODE REVIEW

**Comment by ioquatix** [comment]
Good idea

**Comment by ioquatix** [comment]
What is broken intests?

**Comment by janpio** [comment]
Unrelated breakage because of bundler 2.x release at the beginning of this year I think.

**Comment by ioquatix** [comment]
Thanks for your contribution to improve README. Sorry, I was on mobile so I didn't see what failed.

**Pull request merged**
